name: tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Clone freedom-metal'
        uses: actions/checkout@v2
        with:
          path: freedom-metal
          fetch-depth: 1
          submodules: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build freedom-metal container'
        run: |
          docker build -t freedom-metal \
            -f freedom-metal/docker/Dockerfile \
            freedom-metal

      - name: 'Run Clang code style test'
        run: |
          docker run --rm freedom-metal ./scripts/check-format
